---
 title: "Evolution of maternal deaths between 2000 and 2020 around the World"
subtitle: ""
author: "Manon Lepicard"
date: "2024-04-11"
format: 
  html:
  theme: Solarized
toc: true #table of content
execute: 
  echo: false
warning: false
message: false
lightbox: auto #overview
backgroundcolor: "#FAF3F1"
---
BLabkbakbakbakb

---

```{r}
install.packages("plotly")
install.packages("tidyverse")

library(tidyverse)
library(plotly)
library(ggplot2)
library(viridisLite)

#defining data
localisation <- read_delim("Documents/dataanalyse/Ok/localisation.csv", 
                           delim = ";", escape_double = FALSE, trim_ws = TRUE)
imp_data <- read_delim("Documents/dataanalyse/Ok/all-data.csv", 
                       delim = ";", escape_double = FALSE, trim_ws = TRUE)
maternal_mortality_2000 <- read_delim("Documents/dataanalyse/Ok/maternal_mortality_2000.csv", 
                                      delim = ";", escape_double = FALSE, trim_ws = TRUE)
maternal_mortality_2020 <- read_delim("Documents/dataanalyse/Ok/maternal_mortality_2020.csv", 
                                      delim = ";", escape_double = FALSE, trim_ws = TRUE)

#my colours
my_colours <- c("#faf7f1","#98C2D1","#5D9693","#B74A63","#3D668C", "#E1F8FF", "#FAF3F1")
my_colours_map <- map(my_colours[4],function(x) colorRampPalette(c(my_colours[2],x))(5))
my_colours_map2 <- c(my_colours_map)
my_gradient <- c("#98C2D1", "#94a6f7", "#db4fa3", "#d62b60", "#B74A63")

#joining my data
data_join <- imp_data %>%
  full_join(localisation, by=join_by(country,code))%>%
  full_join(maternal_mortality_2020, by=join_by(country, code, year))%>%
  full_join(maternal_mortality_2000, by=join_by(country, code, year))

#map 
map_world <- map_data("world")
map_world$region <- as.character(map_world$region)
map_world$region[map_world$region == "USA"] <- "United States of America"
map_world$region[map_world$region == "UK"] <- "United Kingdom"
map_world$region[map_world$region == "Republic of Congo"] <- "Republic of the Congo"
map_world$region[map_world$region == "Democratic Republic of the Congo"] <- "Congo"

map_data_join <- full_join(data_join, map_world, by = c("country"="region"))

#data for graph
data_2000 <- filter(map_data_join, year == 2000)
data_2020 <- filter(map_data_join, year == 2020)
data_2000_2020 <- full_join(data_2020, data_2000)
health_exp <- full_join(select(imp_data, country, GDP_per_capita, Current_health_exp, year), localisation)

```

---
Test
---

```{r}
#map 
map_world <- map_data("world")
map_world$region <- as.character(map_world$region)
map_world$region[map_world$region == "USA"] <- "United States of America"
map_world$region[map_world$region == "UK"] <- "United Kingdom"
map_world$region[map_world$region == "Republic of Congo"] <- "Republic of the Congo"
map_world$region[map_world$region == "Democratic Republic of the Congo"] <- "Congo"

map_data_join <- full_join(data_join, map_world, by = c("country"="region"))

```

---

---
